### ISSUE TITLE
Forbidden (HTTP 403) error when running script with API call automatically

### ISSUE THREAD

**Issue by mdemete** [hrbrmstr/darksky#16]
Hi! My apologies if this issue has been documented before.

When I run an Rscript using the API manually, it works perfectly, but when I try to run it automatically (with Cron in Ubuntu), I get the following error: 
Error in get_current_forecast(...)  :  Forbidden (HTTP 403).
Execution halted

I wonder if I am using incorrectly the package (which so far has been great, thank you), or should I contact Darksky directly? Thank you!

**Comment by hrbrmstr** [comment]
No apologies necessary!

I suspect this is an issue due to environment variables not being available to the script when it's run via cron.

See if the answers here help: https://stackoverflow.com/questions/2229825/where-can-i-set-environment-variables-that-crontab-will-use

If not, ping back here and I'll see if we can't get to the bottom of it.

**Comment by mdemete** [comment]
Thank you! Indeed I had to set the API key separately for cron.

I've been struggling with this for hours, this option has not crossed my mind, silly me.
Thanks again, have a great day!
